import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css"
import { StoreContextProvider } from "./context/storeContext";
import { AuthContextProvider } from "./context/authContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreContextProvider>
          <AuthContextProvider>
            {children}
          </AuthContextProvider>
        </StoreContextProvider>
      </body>
    </html>
  );
}
